language: node_js

os:
  - linux
  - osx

node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

script:
  - npm run coveralls || echo "push to coveralls failed"

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never
    on_failure: always
